services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: chat-backend
    ports:
      - "443:443"
    networks:
      - chat-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: chat-frontend
    ports:
      - "3000:3000"
    environment:
      - BACKEND_URL=http://chat-backend:443
    networks:
      - chat-network
    depends_on:
      - backend

networks:
  chat-network:
    driver: bridge
