name: Build & Deploy Backend
on:
  push:
    branches: [main]
permissions:
  contents: read
  packages: write
jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.REPO_OWNER }}
          password: ${{ secrets.GHCR_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_IMAGE }}

  deploy:
    name: Deploy to OCI
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Decode SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" | base64 --decode > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key

      - name: Deploy to Server
        run: |
          ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} << 'EOF'
            echo "Successfully connected to the server!"
            echo "Logging into GitHub Container Registry..."
            # Note: The secrets are not expanded here because of the 'EOF'
            # The variables need to be passed differently.
            # This will be fixed in the next step if needed, let's confirm connection first.
            
            echo "Deployment initiated..."
            # For now, just test the connection
            ls -la
          EOF

