    name: Build & Deploy Backend
    on:
      push:
        branches: [main]
    permissions:
      contents: read
      packages: write
    jobs:
      build:
        name: Build Docker Image
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          - uses: docker/setup-buildx-action@v3
          - uses: docker/login-action@v3
            with:
              registry: ghcr.io
              username: ${{ secrets.REPO_OWNER }}
              password: ${{ secrets.GHCR_TOKEN }}
          - uses: docker/build-push-action@v5
            with:
              context: ./backend
              file: ./backend/Dockerfile
              push: true
              tags: ${{ secrets.DOCKER_IMAGE }}

      deploy:
        name: Deploy to OCI
        needs: build
        runs-on: ubuntu-latest
        steps:
          - name: Decode SSH Key
            run: |
              mkdir -p ~/.ssh
              echo "${{ secrets.DEPLOY_KEY }}" | base64 --decode > ~/.ssh/deploy_key
              chmod 600 ~/.ssh/deploy_key

          - name: Deploy to Server
            run: |
              ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} << EOF
                echo "Successfully connected to the server!"
                echo "Logging into GitHub Container Registry..."
                echo "${{ secrets.GHCR_TOKEN }}" | sudo docker login ghcr.io -u "${{ secrets.REPO_OWNER }}" --password-stdin
                
                echo "Pulling the latest Docker image..."
                sudo docker pull "${{ secrets.DOCKER_IMAGE }}"
                
                echo "Stopping and removing the old container..."
                sudo docker stop backend-app || true
                sudo docker rm backend-app || true
                
                echo "Starting the new container..."
                sudo docker run -d --restart=always --name backend-app -p 8080:8080 "${{ secrets.DOCKER_IMAGE }}"
                
                echo "Deployment complete!"
              EOF